[profile.default]
src = 'contracts'
out = 'forge-artifacts'
libs = ['node_modules']
test = 'test/foundry'
cache_path  = 'forge-cache'
allow_paths = ['../', '../../node_modules/']
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
remappings = [
    'vault/=../vault/',
    'pool-weighted/=../pool-weighted/',
    'solidity-utils/=../solidity-utils/',
    'ds-test/=../../node_modules/forge-std/lib/ds-test/src/',
    'forge-std/=../../node_modules/forge-std/src/',
    '@openzeppelin/=../../node_modules/@openzeppelin/',
    'permit2/=../../node_modules/permit2/',
    '@balancer-labs/=../../node_modules/@balancer-labs/',
    'forge-gas-snapshot/=../../node_modules/forge-gas-snapshot/src/'
]
optimizer = true
optimizer_runs = 999
solc_version = '0.8.26'
auto_detect_solc = false
evm_version = 'cancun'
ignored_error_codes = [2394, 5574, 3860] # Transient storage, code size

[fuzz]
runs = 10000
max_test_rejects = 60000

[profile.forkfuzz.fuzz]
runs = 1000
max_test_rejects = 60000

[profile.coverage.fuzz]
runs = 100
max_test_rejects = 60000

[profile.intense.fuzz]
verbosity = 3
runs = 100000
max_test_rejects = 600000

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
