name: Setup

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.15
    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
    - name: Yarn
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Install lcov
      shell: bash
      run: sudo apt-get install lcov
