/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as temporarilyPausableSol from "./TemporarilyPausable.sol";
export type { temporarilyPausableSol };
