/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  PausableConstants,
  PausableConstantsInterface,
} from "../../../../contracts/helpers/TemporarilyPausable.sol/PausableConstants";

const _abi = [
  {
    inputs: [],
    name: "MAX_BUFFER_PERIOD_DURATION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_PAUSE_WINDOW_DURATION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x609d610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603d5760003560e01c80638b19548d146042578063fc5e93fe14605d575b600080fd5b604b6276a70081565b60405190815260200160405180910390f35b604b630163f5008156fea2646970667358221220e3aef4e3b0f9d01977294b0dd11eaf99e733f27848ccd59ee55850bdcb563e9464736f6c63430008120033";

type PausableConstantsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PausableConstantsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PausableConstants__factory extends ContractFactory {
  constructor(...args: PausableConstantsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PausableConstants> {
    return super.deploy(overrides || {}) as Promise<PausableConstants>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PausableConstants {
    return super.attach(address) as PausableConstants;
  }
  override connect(signer: Signer): PausableConstants__factory {
    return super.connect(signer) as PausableConstants__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PausableConstantsInterface {
    return new utils.Interface(_abi) as PausableConstantsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PausableConstants {
    return new Contract(address, _abi, signerOrProvider) as PausableConstants;
  }
}
