/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PausableConstants } from "./PausableConstants";
export type { TemporarilyPausable } from "./TemporarilyPausable";
