/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface PausableConstantsInterface extends utils.Interface {
  functions: {
    "MAX_BUFFER_PERIOD_DURATION()": FunctionFragment;
    "MAX_PAUSE_WINDOW_DURATION()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_BUFFER_PERIOD_DURATION"
      | "MAX_PAUSE_WINDOW_DURATION"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_BUFFER_PERIOD_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PAUSE_WINDOW_DURATION",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BUFFER_PERIOD_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PAUSE_WINDOW_DURATION",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PausableConstants extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PausableConstantsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_BUFFER_PERIOD_DURATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_PAUSE_WINDOW_DURATION(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  MAX_BUFFER_PERIOD_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_PAUSE_WINDOW_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    MAX_BUFFER_PERIOD_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_PAUSE_WINDOW_DURATION(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    MAX_BUFFER_PERIOD_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_PAUSE_WINDOW_DURATION(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_BUFFER_PERIOD_DURATION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_PAUSE_WINDOW_DURATION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
