/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface TemporarilyPausableMockInterface extends utils.Interface {
  functions: {
    "getBufferPeriodEndTime()": FunctionFragment;
    "getMaxBufferPeriodDuration()": FunctionFragment;
    "getMaxPauseWindowDuration()": FunctionFragment;
    "getPauseWindowEndTime()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getBufferPeriodEndTime"
      | "getMaxBufferPeriodDuration"
      | "getMaxPauseWindowDuration"
      | "getPauseWindowEndTime"
      | "pause"
      | "paused"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBufferPeriodEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxBufferPeriodDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxPauseWindowDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPauseWindowEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getBufferPeriodEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxBufferPeriodDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxPauseWindowDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauseWindowEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface TemporarilyPausableMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TemporarilyPausableMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getBufferPeriodEndTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMaxBufferPeriodDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMaxPauseWindowDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPauseWindowEndTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getBufferPeriodEndTime(overrides?: CallOverrides): Promise<BigNumber>;

  getMaxBufferPeriodDuration(overrides?: CallOverrides): Promise<BigNumber>;

  getMaxPauseWindowDuration(overrides?: CallOverrides): Promise<BigNumber>;

  getPauseWindowEndTime(overrides?: CallOverrides): Promise<BigNumber>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getBufferPeriodEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxBufferPeriodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxPauseWindowDuration(overrides?: CallOverrides): Promise<BigNumber>;

    getPauseWindowEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    unpause(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    getBufferPeriodEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxBufferPeriodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxPauseWindowDuration(overrides?: CallOverrides): Promise<BigNumber>;

    getPauseWindowEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBufferPeriodEndTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaxBufferPeriodDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaxPauseWindowDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPauseWindowEndTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
